---

- name: Set boolean valued key for application domain
  tags: macos
  notify: RestartFinder
  community.general.osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  with_items: "{{ mac_settings }}"
