---

- name: Check if Homebrew is installed
  tags: homebrew
  register: homebrew_check
  ansible.builtin.stat:
    path: /opt/homebrew/bin/brew

- name: Check for sudo session when installing Homebrew
  tags: homebrew
  become: true
  when: not homebrew_check.stat.exists
  ansible.builtin.command: ls
  changed_when: false

- name: Installing Homebrew
  tags: homebrew
  when: not homebrew_check.stat.exists
  vars:
    homebrew_url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
  ansible.builtin.shell: /bin/bash -c "$(curl -fsSL {{ homebrew_url  }})"

- name: Ensure Homebrew is loaded in zsh
  tags: homebrew
  when: homebrew_check.stat.exists
  ansible.builtin.lineinfile:
    insertbefore: BOF
    path: "{{ user_home }}/.zshrc"
    line: 'eval "$(/opt/homebrew/bin/brew shellenv)"'
  
- name: Updating Homebrew
  tags: homebrew
  when: homebrew_check.stat.exists
  ansible.builtin.homebrew:
    update_homebrew: true

- name: Upgrading Homebrew Packages
  tags: homebrew
  when: homebrew_check.stat.exists
  until: result is successful
  register: result
  ansible.builtin.homebrew:
    upgrade_all: "{{ upgrade_homebrew_packages }}"

- name: Installing Homebrew Cask Packages
  tags: homebrew
  when: homebrew_check.stat.exists
  register: result
  until: result is successful
  ansible.builtin.homebrew_cask:
    name: "{{ brew_cask_packages }}"
    state: present

- name: Installing Homebrew Packages
  tags: homebrew
  when: homebrew_check.stat.exists
  register: result
  until: result is successful
  ansible.builtin.homebrew:
    name: "{{ brew_packages }}"
    state: present
